In [1]:
import numpy as np
import scipy.sparse as sparse   

In [2]:
sparse_matrix = np.array([[0,0,3],
                        [0,5,0],
                        [7,0,0]])

In [3]:
sparse_matrix_1 = sparse.csr_matrix(sparse_matrix)
print(sparse_matrix_1)

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 3 stored elements and shape (3, 3)>
  Coords	Values
  (0, 2)	3
  (1, 1)	5
  (2, 0)	7


In [4]:
print(sparse_matrix_1[0,2])

3


In [5]:
print(sparse_matrix_1.ndim)
print(sparse_matrix_1.shape)
print(sparse_matrix_1.size)
print(np.max(sparse_matrix_1,axis=0))
print(np.mean(sparse_matrix_1,axis=1))
print(np.std(sparse_matrix,axis=1))
print(np.var(sparse_matrix))

2
(3, 3)
3
<COOrdinate sparse matrix of dtype 'int64'
	with 3 stored elements and shape (1, 3)>
  Coords	Values
  (0, 0)	7
  (0, 1)	5
  (0, 2)	3
[[1.        ]
 [1.66666667]
 [2.33333333]]
[1.41421356 2.3570226  3.29983165]
6.444444444444444


reshape method

In [6]:
print(sparse_matrix.reshape(1,-1))
print(sparse_matrix.flatten())

[[0 0 3 0 5 0 7 0 0]]
[0 0 3 0 5 0 7 0 0]


Transpose of matrix

In [7]:
print(sparse_matrix.T)

[[0 0 7]
 [0 5 0]
 [3 0 0]]


 <font size="6">Rank of matrix</font>

In [8]:
print(np.linalg.matrix_rank(sparse_matrix))
print(np.linalg.det(sparse_matrix))

3
-104.99999999999997


*Diagonal of matrix*

In [9]:
sparse_matrix.diagonal()
sparse_matrix.diagonal(offset=1) #diagonal above main diagonal
sparse_matrix.diagonal(offset=-1) #diagonal below main diagonal

array([0, 0])

<h3>Trace (sum of diagnal elements) of matrix</h3>

In [10]:
eigenvalues, eigenvectors = np.linalg.eig(sparse_matrix)
print("Eigenvalues:", eigenvalues)  
print("Eigenvectors:\n", eigenvectors)
sparse_matrix @ sparse_matrix

Eigenvalues: [ 4.58257569 -4.58257569  5.        ]
Eigenvectors:
 [[ 0.54772256 -0.54772256  0.        ]
 [ 0.          0.          1.        ]
 [ 0.83666003  0.83666003  0.        ]]


array([[21,  0,  0],
       [ 0, 25,  0],
       [ 0,  0, 21]])

<font size = "5">Inverse </font>

In [14]:
print(np.linalg.inv(sparse_matrix))

[[0.         0.         0.14285714]
 [0.         0.2        0.        ]
 [0.33333333 0.         0.        ]]


<h2>Random number</h2>

In [ ]:
np.random.seed(0)
np.random.random(10)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ,
       0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152])

: 